import React, { useState, useEffect } from 'react';
import { useNavigate } from '../services/dataService.ts';
import { supabase } from '../services/supabaseClient.ts';
import { getStyles, createStyle, deleteStyle, updateStyle } from '../services/styleService.ts';
import { getSchedule, createSession, updateSession, deleteSession } from '../services/scheduleService.ts';
import { getInquiries, deleteInquiry } from '../services/contactService.ts';
import { getPrograms, createProgram, updateProgram, deleteProgram } from '../services/programService.ts';
import { getPricingPlans, createPricingPlan, updatePricingPlan, deletePricingPlan } from '../services/pricingService.ts';
import { getBlogPosts, createBlogPost, updateBlogPost, deleteBlogPost } from '../services/blogService.ts';
import { getFeedback, createFeedback, updateFeedback, deleteFeedback } from '../services/feedbackService.ts';
import { YogaStyle, ClassSession, ContactInquiry, Course, PricingPlan, BlogPost, CustomerFeedback } from '../types.ts';
import { 
  Calendar, 
  BookOpen, 
  CreditCard, 
  PenTool, 
  LogOut, 
  Menu, 
  X,
  Leaf,
  Plus,
  Edit2,
  Trash2,
  Search,
  Upload,
  XCircle,
  Loader2,
  Image as ImageIcon,
  Database,
  Copy,
  Check,
  Terminal,
  Clock,
  MapPin,
  User,
  MessageSquare,
  IndianRupee,
  FileText,
  Eye,
  EyeOff,
  Download,
  ArrowUpDown,
  ChevronLeft,
  ChevronRight,
  Star,
  Quote
} from 'lucide-react';
// @ts-ignore - bypassing broken framer-motion types in this environment
import { motion as framerMotion, AnimatePresence } from 'framer-motion';
const motion = framerMotion as any;

const SETUP_SQL = `-- Run this in Supabase SQL Editor to RESET and DISABLE RLS

/* =========================================================
   STEP 0 — DROP ALL POLICIES (CLEAN RESET)
   ========================================================= */

-- CONTACT INQUIRIES
drop policy if exists "public_insert_contact_inquiries" on public.contact_inquiries;
drop policy if exists "admin_full_access_contact_inquiries" on public.contact_inquiries;

-- COURSES
drop policy if exists "public_read_courses" on public.courses;
drop policy if exists "admin_manage_courses" on public.courses;

-- BLOG POSTS
drop policy if exists "public_read_published_posts" on public.blog_posts;
drop policy if exists "admin_manage_blog_posts" on public.blog_posts;

-- BLOG COMMENTS
drop policy if exists "public_read_comments" on public.blog_comments;
drop policy if exists "public_insert_comments" on public.blog_comments;
drop policy if exists "admin_delete_comments" on public.blog_comments;

-- PRICING PLANS
drop policy if exists "public_read_pricing_plans" on public.pricing_plans;
drop policy if exists "admin_manage_pricing_plans" on public.pricing_plans;

-- YOGA STYLES
drop policy if exists "public_read_yoga_styles" on public.yoga_styles;
drop policy if exists "admin_manage_yoga_styles" on public.yoga_styles;

-- CLASS SESSIONS
drop policy if exists "public_read_class_sessions" on public.class_sessions;
drop policy if exists "admin_manage_class_sessions" on public.class_sessions;

-- CUSTOMER FEEDBACK
drop policy if exists "public_read_feedback" on public.customer_feedback;
drop policy if exists "admin_manage_feedback" on public.customer_feedback;


/* =========================================================
   STEP 1 — FORCE DISABLE ROW LEVEL SECURITY
   ========================================================= */

alter table if exists public.contact_inquiries disable row level security;
alter table if exists public.courses disable row level security;
alter table if exists public.blog_posts disable row level security;
alter table if exists public.blog_comments disable row level security;
alter table if exists public.pricing_plans disable row level security;
alter table if exists public.yoga_styles disable row level security;
alter table if exists public.class_sessions disable row level security;
alter table if exists public.customer_feedback disable row level security;


/* =========================================================
   STEP 2 — TABLE CREATION ONLY (NO RLS, NO POLICIES)
   ========================================================= */

-- 1. CONTACT INQUIRIES
create table if not exists public.contact_inquiries (
  id uuid default gen_random_uuid() primary key,
  created_at timestamptz not null default timezone('utc', now()),
  first_name text,
  last_name text,
  email text,
  phone_number text,
  message text,
  inquiry_type text
);

-- 2. COURSES
create table if not exists public.courses (
  slug text primary key,
  title text not null,
  description text,
  level text,
  duration text,
  price numeric,
  image text,
  badge text,
  pdf_url text,
  created_at timestamptz not null default timezone('utc', now())
);

-- 3. BLOG POSTS
create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text,
  content text,
  image text,
  category text,
  published boolean default false,
  likes int default 0,
  created_at timestamptz not null default timezone('utc', now())
);

-- 4. BLOG COMMENTS
create table if not exists public.blog_comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.blog_posts(id) on delete cascade,
  user_name text,
  user_email text,
  content text not null,
  is_admin boolean default false,
  created_at timestamptz not null default timezone('utc', now())
);

-- 5. PRICING PLANS
create table if not exists public.pricing_plans (
  id bigint generated by default as identity primary key,
  name text,
  price text,
  period text,
  benefits text[],
  highlight boolean,
  created_at timestamptz not null default timezone('utc', now())
);

-- 6. YOGA STYLES
create table if not exists public.yoga_styles (
  slug text primary key,
  name text,
  description text,
  benefits text[],
  difficulty text,
  duration text,
  image text,
  created_at timestamptz not null default timezone('utc', now())
);

-- 7. CLASS SESSIONS
create table if not exists public.class_sessions (
  id bigint generated by default as identity primary key,
  day text,
  time text,
  class_type text,
  instructor text,
  location text,
  level text,
  created_at timestamptz not null default timezone('utc', now())
);

-- 8. CUSTOMER FEEDBACK
create table if not exists public.customer_feedback (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  quote text not null,
  rating int default 5,
  image text,
  created_at timestamptz not null default timezone('utc', now())
);
`;

// Helper Components
const Modal = ({ isOpen, onClose, title, children }: { isOpen: boolean; onClose: () => void; title: string; children?: React.ReactNode }) => {
  if (!isOpen) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" onClick={onClose}>
      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        onClick={e => e.stopPropagation()}
        className="bg-white rounded-2xl shadow-xl w-full max-w-2xl max-h-[90vh] overflow-y-auto"
      >
        <div className="flex justify-between items-center p-6 border-b border-gray-100 sticky top-0 bg-white z-10">
          <h3 className="font-serif text-2xl font-medium text-deep-green">{title}</h3>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-full text-gray-500 transition-colors"><X size={20} /></button>
        </div>
        <div className="p-6">
          {children}
        </div>
      </motion.div>
    </div>
  );
};

const DashboardSection = ({ title, description, onAdd, children, extraHeaderAction, hideAddButton }: any) => (
  <div className="space-y-6">
    <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
      <div>
        <h2 className="font-serif text-3xl text-deep-green">{title}</h2>
        <p className="text-gray-500 mt-1">{description}</p>
      </div>
      <div className="flex items-center gap-3">
        {extraHeaderAction}
        {!hideAddButton && (
            <button onClick={onAdd} className="bg-sage-green text-white px-4 py-2 rounded-lg font-medium hover:bg-deep-green transition-colors flex items-center gap-2 shadow-sm hover:shadow-md">
            <Plus size={18} /> Add New
            </button>
        )}
      </div>
    </div>
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      {children}
    </div>
  </div>
);

const SqlHelpBox = ({ sql, onCopy, copied }: any) => (
  <div className="p-6 bg-gray-50 border-b border-gray-100">
    <div className="bg-gray-900 rounded-xl overflow-hidden shadow-inner">
      <div className="flex justify-between items-center px-4 py-2 bg-gray-800 border-b border-gray-700">
        <span className="text-xs font-mono text-gray-400 flex items-center gap-2"><Database size={12} /> SQL Setup Script</span>
        <button onClick={onCopy} className="text-xs flex items-center gap-1 text-gray-400 hover:text-white transition-colors">
          {copied ? <Check size={12} className="text-green-400" /> : <Copy size={12} />} {copied ? 'Copied' : 'Copy'}
        </button>
      </div>
      <div className="p-4 overflow-x-auto max-h-40 custom-scrollbar">
        <pre className="text-xs font-mono text-gray-300 whitespace-pre">{sql}</pre>
      </div>
    </div>
    <div className="mt-2 flex items-start gap-2 text-xs text-amber-700 bg-amber-50 p-2 rounded border border-amber-100">
      <Terminal size={14} className="mt-0.5 shrink-0" />
      <p><b>Action Required:</b> Run this SQL in Supabase to create tables (if they don't exist).</p>
    </div>
  </div>
);

const EmptyState = ({ message }: { message: string }) => (
  <div className="p-12 text-center">
    <div className="w-16 h-16 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-4 text-gray-300">
      <Database size={32} />
    </div>
    <p className="text-gray-500 font-medium">{message}</p>
  </div>
);

const Table = ({ headers, rows }: { headers: string[], rows: React.ReactNode[] }) => (
  <div className="overflow-x-auto">
    <table className="w-full text-left border-collapse">
      <thead>
        <tr className="bg-gray-50/50 border-b border-gray-100 text-xs font-semibold text-gray-500 uppercase tracking-wider">
          {headers.map((h, i) => <th key={i} className="px-6 py-4">{h}</th>)}
        </tr>
      </thead>
      <tbody className="divide-y divide-gray-50">
        {rows}
      </tbody>
    </table>
  </div>
);

const Badge = ({ children, type }: { children?: React.ReactNode, type?: string }) => {
  let colorClass = "bg-gray-100 text-gray-600";
  if (type === 'Beginner') colorClass = "bg-green-50 text-green-700 border border-green-100";
  else if (type === 'Intermediate') colorClass = "bg-yellow-50 text-yellow-700 border border-yellow-100";
  else if (type === 'Advanced') colorClass = "bg-orange-50 text-orange-700 border border-orange-100";
  else if (type === 'published') colorClass = "bg-blue-50 text-blue-700 border border-blue-100";
  else if (type === 'draft') colorClass = "bg-gray-100 text-gray-500 border border-gray-200";
  
  return <span className={`px-2.5 py-1 rounded-md text-xs font-medium ${colorClass}`}>{children}</span>;
};

const ActionButtons = ({ onEdit, onDelete }: { onEdit: () => void, onDelete: () => void }) => (
  <div className="flex items-center gap-2">
    <button onClick={onEdit} className="p-1.5 text-gray-500 hover:text-sage-green hover:bg-sage-green/10 rounded-md transition-colors" title="Edit">
      <Edit2 size={16} />
    </button>
    <button onClick={onDelete} className="p-1.5 text-gray-500 hover:text-red-600 hover:bg-red-50 rounded-md transition-colors" title="Delete">
      <Trash2 size={16} />
    </button>
  </div>
);

const AdminDashboard = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('styles');
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [userEmail, setUserEmail] = useState('');
  
  // Error Handling State
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [showSqlHelp, setShowSqlHelp] = useState(false);
  const [copied, setCopied] = useState(false);

  // --- State for Data ---
  const [styles, setStyles] = useState<YogaStyle[]>([]);
  const [scheduleData, setScheduleData] = useState<ClassSession[]>([]);
  const [inquiries, setInquiries] = useState<ContactInquiry[]>([]);
  const [programs, setPrograms] = useState<Course[]>([]);
  const [pricingPlansData, setPricingPlansData] = useState<PricingPlan[]>([]);
  const [blogPosts, setBlogPosts] = useState<BlogPost[]>([]);
  const [feedback, setFeedback] = useState<CustomerFeedback[]>([]);

  // --- Messages Tab Specific State ---
  const [messagePage, setMessagePage] = useState(1);
  const [messageSort, setMessageSort] = useState<{key: keyof ContactInquiry, direction: 'asc' | 'desc'}>({ key: 'created_at', direction: 'desc' });
  const messagesPerPage = 20;

  // --- Modals & Forms State ---
  const [isStyleModalOpen, setIsStyleModalOpen] = useState(false);
  const [isScheduleModalOpen, setIsScheduleModalOpen] = useState(false);
  const [isProgramModalOpen, setIsProgramModalOpen] = useState(false);
  const [isPricingModalOpen, setIsPricingModalOpen] = useState(false);
  const [isBlogModalOpen, setIsBlogModalOpen] = useState(false);
  const [isFeedbackModalOpen, setIsFeedbackModalOpen] = useState(false);

  const [isSubmitting, setIsSubmitting] = useState(false);
  
  // File States
  const [selectedImage, setSelectedImage] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [selectedPdf, setSelectedPdf] = useState<File | null>(null);

  // Editing Selection State
  const [editingStyle, setEditingStyle] = useState<YogaStyle | null>(null);
  const [editingSession, setEditingSession] = useState<ClassSession | null>(null);
  const [editingProgram, setEditingProgram] = useState<Course | null>(null);
  const [editingPlan, setEditingPlan] = useState<PricingPlan | null>(null);
  const [editingPost, setEditingPost] = useState<BlogPost | null>(null);
  const [editingFeedback, setEditingFeedback] = useState<CustomerFeedback | null>(null);

  // Form Data States
  const [styleFormData, setStyleFormData] = useState({
    name: '',
    description: '',
    benefits: '',
    difficulty: 'Beginner',
    duration: '',
  });

  const [scheduleFormData, setScheduleFormData] = useState({
    day: 'Monday',
    time: '',
    classType: '',
    instructor: '',
    location: '',
    level: 'All Levels'
  });

  const [programFormData, setProgramFormData] = useState({
    title: '',
    description: '',
    level: 'All Levels',
    duration: '',
    price: '',
    badge: ''
  });

  const [pricingFormData, setPricingFormData] = useState({
    name: '',
    price: '',
    period: 'per month',
    benefits: '',
    highlight: false
  });
  
  const [blogFormData, setBlogFormData] = useState({
      title: '',
      slug: '',
      excerpt: '',
      content: '',
      category: 'Wellness',
      published: false,
      image: ''
  });

  const [feedbackFormData, setFeedbackFormData] = useState({
      name: '',
      role: '',
      quote: '',
      rating: 5,
      image: ''
  });

  // Protect the route and fetch initial data
  useEffect(() => {
    const init = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        navigate('/admin');
        return;
      }
      setUserEmail(session.user.email || 'Admin');
      
      try {
        await fetchAllData();
      } catch (error: any) {
        handleError(error);
      } finally {
        setIsLoading(false);
      }
    };
    init();
  }, [navigate]);

  const fetchAllData = async () => {
    setFetchError(null);
    try {
      const [fetchedStyles, fetchedSchedule, fetchedInquiries, fetchedPrograms, fetchedPricing, fetchedPosts, fetchedFeedback] = await Promise.all([
        getStyles(),
        getSchedule(),
        getInquiries(),
        getPrograms(),
        getPricingPlans(),
        getBlogPosts(false), // Fetch ALL posts including drafts
        getFeedback()
      ]);
      setStyles(fetchedStyles);
      setScheduleData(sortSchedule(fetchedSchedule));
      setInquiries(fetchedInquiries);
      setPrograms(fetchedPrograms);
      setPricingPlansData(fetchedPricing);
      setBlogPosts(fetchedPosts);
      setFeedback(fetchedFeedback);
      
      if (fetchedStyles.length > 0 || fetchedSchedule.length > 0 || fetchedInquiries.length > 0) {
        setShowSqlHelp(false);
      }
    } catch (error: any) {
      handleError(error);
    }
  };

  const handleError = (error: any) => {
    console.error("Data Fetch Error:", error);
    const errMsg = error.message || 'Unknown error';
    setFetchError(errMsg);
    if (errMsg.includes('relation') || errMsg.includes('column') || errMsg.includes('policy')) {
        setShowSqlHelp(true);
    }
  };

  const sortSchedule = (data: ClassSession[]) => {
    const daysOrder = { 'Monday': 1, 'Tuesday': 2, 'Wednesday': 3, 'Thursday': 4, 'Friday': 5, 'Saturday': 6, 'Sunday': 7 };
    return [...data].sort((a, b) => {
      const dayDiff = (daysOrder[a.day as keyof typeof daysOrder] || 8) - (daysOrder[b.day as keyof typeof daysOrder] || 8);
      if (dayDiff !== 0) return dayDiff;
      return a.time.localeCompare(b.time);
    });
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
    navigate('/admin');
  };
  
  const handleCopySql = () => {
      navigator.clipboard.writeText(SETUP_SQL);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
  };

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setSelectedImage(file);
      setImagePreview(URL.createObjectURL(file));
    }
  };

  const handlePdfChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setSelectedPdf(e.target.files[0]);
    }
  };

  // --- HELPER: Date Formatter (dd-mm-yyyy) ---
  const formatAdminDate = (dateString: string) => {
    if (!dateString) return '-';
    const date = new Date(dateString);
    const day = date.getDate().toString().padStart(2, '0');
    const month = (date.getMonth() + 1).toString().padStart(2, '0');
    const year = date.getFullYear();
    return `${day}-${month}-${year}`;
  };

  // --- HELPER: Export to Excel (CSV with BOM) ---
  const exportInquiriesToCSV = () => {
    // 1. Define Headers that match the visual table
    const headers = ['Date', 'Type', 'First Name', 'Last Name', 'Email', 'Phone', 'Message'];
    
    // 2. Map data
    const rows = inquiries.map(item => [
        formatAdminDate(item.created_at),
        item.inquiry_type || '',
        item.first_name || '',
        item.last_name || '',
        item.email || '',
        item.phone_number ? `'${item.phone_number}` : '', // Force Excel to treat as string to prevent scientific notation
        item.message || ''
    ]);

    // 3. Convert to CSV string, properly handling quotes and commas
    const csvContent = [
        headers.join(','),
        ...rows.map(row => row.map(cell => {
            // Escape double quotes by doubling them
            const escaped = String(cell).replace(/"/g, '""');
            // Wrap in double quotes
            return `"${escaped}"`;
        }).join(','))
    ].join('\r\n'); // Use CRLF for Windows/Excel compatibility

    // 4. Create Blob with BOM (Byte Order Mark) for Excel UTF-8 recognition
    const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
    
    // 5. Trigger Download
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Meraki_Inquiries_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // --- STYLE HANDLERS ---
  const resetStyleForm = () => {
    setStyleFormData({ name: '', description: '', benefits: '', difficulty: 'Beginner', duration: '' });
    setSelectedImage(null);
    setImagePreview(null);
    setEditingStyle(null);
  };

  const handleStyleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      const commonData = {
        name: styleFormData.name,
        description: styleFormData.description,
        difficulty: styleFormData.difficulty as any,
        duration: styleFormData.duration,
        benefits: styleFormData.benefits.split(',').map(b => b.trim()),
      };

      if (editingStyle) {
        const result = await updateStyle(editingStyle.slug, { ...commonData, image: editingStyle.image }, selectedImage);
        setStyles(styles.map(s => s.slug === editingStyle.slug ? result : s));
      } else {
        const result = await createStyle({ ...commonData, image: '' }, selectedImage);
        setStyles([result, ...styles]);
      }
      setIsStyleModalOpen(false);
      resetStyleForm();
    } catch (error: any) {
      alert(`Error: ${error.message}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDeleteStyle = async (slug: string, imageUrl: string) => {
    if (window.confirm('Are you sure?')) {
      try {
        await deleteStyle(slug, imageUrl);
        setStyles(styles.filter(s => s.slug !== slug));
      } catch (error: any) { alert(`Failed: ${error.message}`); }
    }
  };

  // --- SCHEDULE HANDLERS ---
  const resetScheduleForm = () => {
    setScheduleFormData({ day: 'Monday', time: '', classType: '', instructor: '', location: '', level: 'All Levels' });
    setEditingSession(null);
  };

  const handleScheduleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      if (editingSession) {
        const updated = await updateSession(editingSession.id, scheduleFormData);
        setScheduleData(sortSchedule(scheduleData.map(s => s.id === editingSession.id ? updated : s)));
      } else {
        const created = await createSession(scheduleFormData);
        setScheduleData(sortSchedule([...scheduleData, created]));
      }
      setIsScheduleModalOpen(false);
      resetScheduleForm();
    } catch (error: any) { alert(`Error: ${error.message}`); } finally { setIsSubmitting(false); }
  };

  const handleDeleteSession = async (id: string) => {
    if (window.confirm('Remove class?')) {
      try {
        await deleteSession(id);
        setScheduleData(scheduleData.filter(s => s.id !== id));
      } catch (error: any) { alert(`Failed: ${error.message}`); }
    }
  };

  // --- PROGRAM HANDLERS ---
  const resetProgramForm = () => {
    setProgramFormData({ title: '', description: '', level: 'All Levels', duration: '', price: '', badge: '' });
    setSelectedImage(null);
    setSelectedPdf(null);
    setImagePreview(null);
    setEditingProgram(null);
  };

  const handleProgramSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      const commonData = {
        title: programFormData.title,
        description: programFormData.description,
        level: programFormData.level,
        duration: programFormData.duration,
        price: parseFloat(programFormData.price) || 0,
        badge: programFormData.badge
      };

      if (editingProgram) {
        const result = await updateProgram(editingProgram.slug, { ...commonData, image: editingProgram.image, pdf_url: editingProgram.pdf_url }, selectedImage, selectedPdf);
        setPrograms(programs.map(p => p.slug === editingProgram.slug ? result : p));
      } else {
        const result = await createProgram({ ...commonData, image: '', pdf_url: '' }, selectedImage, selectedPdf);
        setPrograms([result, ...programs]);
      }
      setIsProgramModalOpen(false);
      resetProgramForm();
    } catch (error: any) { alert(`Error: ${error.message}`); } finally { setIsSubmitting(false); }
  };

  const handleDeleteProgram = async (slug: string) => {
    if (window.confirm('Delete this program?')) {
      try {
        await deleteProgram(slug);
        setPrograms(programs.filter(p => p.slug !== slug));
      } catch (error: any) { alert(`Failed: ${error.message}`); }
    }
  };

  // --- PRICING HANDLERS ---
  const resetPricingForm = () => {
    setPricingFormData({ name: '', price: '', period: 'per month', benefits: '', highlight: false });
    setEditingPlan(null);
  };

  const handlePricingSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      const planData = {
        name: pricingFormData.name,
        price: pricingFormData.price,
        period: pricingFormData.period,
        benefits: pricingFormData.benefits.split(',').map(b => b.trim()),
        highlight: pricingFormData.highlight
      };

      if (editingPlan) {
        const result = await updatePricingPlan(editingPlan.id, planData);
        setPricingPlansData(pricingPlansData.map(p => p.id === editingPlan.id ? result : p));
      } else {
        const result = await createPricingPlan(planData);
        setPricingPlansData([...pricingPlansData, result]);
      }
      setIsPricingModalOpen(false);
      resetPricingForm();
    } catch (error: any) { alert(`Error: ${error.message}`); } finally { setIsSubmitting(false); }
  };

  const handleDeletePlan = async (id: string) => {
    if (window.confirm('Delete this pricing plan?')) {
      try {
        await deletePricingPlan(id);
        setPricingPlansData(pricingPlansData.filter(p => p.id !== id));
      } catch (error: any) { alert(`Failed: ${error.message}`); }
    }
  };

  // --- BLOG HANDLERS ---
  const resetBlogForm = () => {
    setBlogFormData({ title: '', slug: '', excerpt: '', content: '', category: 'Wellness', published: false, image: '' });
    setSelectedImage(null);
    setImagePreview(null);
    setEditingPost(null);
  };

  const handleBlogSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      if (editingPost) {
        const result = await updateBlogPost(editingPost.id, blogFormData, selectedImage);
        setBlogPosts(blogPosts.map(p => p.id === editingPost.id ? result : p));
      } else {
        const result = await createBlogPost(blogFormData, selectedImage);
        setBlogPosts([result, ...blogPosts]);
      }
      setIsBlogModalOpen(false);
      resetBlogForm();
    } catch (error: any) { alert(`Error: ${error.message}`); } finally { setIsSubmitting(false); }
  };

  const handleDeletePost = async (id: number) => {
    if (window.confirm('Delete this post?')) {
      try {
        await deleteBlogPost(id);
        setBlogPosts(blogPosts.filter(p => p.id !== id));
      } catch (error: any) { alert(`Failed: ${error.message}`); }
    }
  };


  // --- INQUIRY HANDLERS ---
  const handleDeleteInquiry = async (id: string) => {
    if (window.confirm('Delete message?')) {
      try {
        await deleteInquiry(id);
        setInquiries(inquiries.filter(i => i.id !== id));
      } catch (error: any) { alert(`Failed: ${error.message}`); }
    }
  };

  // --- FEEDBACK HANDLERS ---
  const resetFeedbackForm = () => {
      setFeedbackFormData({ name: '', role: '', quote: '', rating: 5, image: '' });
      setSelectedImage(null);
      setImagePreview(null);
      setEditingFeedback(null);
  };

  const handleFeedbackSubmit = async (e: React.FormEvent) => {
      e.preventDefault();
      setIsSubmitting(true);
      try {
          if (editingFeedback) {
              const result = await updateFeedback(editingFeedback.id, feedbackFormData, selectedImage);
              setFeedback(feedback.map(f => f.id === editingFeedback.id ? result : f));
          } else {
              const result = await createFeedback(feedbackFormData, selectedImage);
              setFeedback([result, ...feedback]);
          }
          setIsFeedbackModalOpen(false);
          resetFeedbackForm();
      } catch (error: any) {
          alert(`Error: ${error.message}`);
      } finally {
          setIsSubmitting(false);
      }
  };

  const handleDeleteFeedback = async (id: number) => {
      if(window.confirm('Delete this feedback?')) {
          try {
              await deleteFeedback(id);
              setFeedback(feedback.filter(f => f.id !== id));
          } catch(error: any) {
              alert(`Failed: ${error.message}`);
          }
      }
  };

  const menuItems = [
    { id: 'styles', label: 'Styles', icon: <Leaf size={20} /> },
    { id: 'schedule', label: 'Schedule', icon: <Calendar size={20} /> },
    { id: 'programs', label: 'Programs', icon: <BookOpen size={20} /> },
    { id: 'pricing', label: 'Pricing', icon: <CreditCard size={20} /> },
    { id: 'messages', label: 'Messages', icon: <MessageSquare size={20} /> },
    { id: 'feedback', label: 'Feedback', icon: <Quote size={20} /> },
    { id: 'blog', label: 'Blog', icon: <PenTool size={20} /> },
  ];

  if (isLoading) {
    return (
      <div className="min-h-screen bg-warm-white flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-deep-green"></div>
      </div>
    );
  }

  // Helper to ensure the price has the rupee symbol
  const formatAdminPrice = (price: string) => {
    if (!price) return '-';
    return price.startsWith('₹') ? price : `₹${price}`;
  };

  const renderContent = () => {
    switch (activeTab) {
      case 'styles':
        return (
          <DashboardSection 
            title="Yoga Styles" 
            description="Manage the different styles of yoga offered at the studio."
            onAdd={() => { resetStyleForm(); setIsStyleModalOpen(true); }}
            extraHeaderAction={<button onClick={() => setShowSqlHelp(!showSqlHelp)} className="text-xs text-gray-500 hover:text-deep-green underline flex items-center gap-1"><Terminal size={14} /> {showSqlHelp ? 'Hide SQL' : 'Show SQL'}</button>}
          >
            {showSqlHelp && <SqlHelpBox sql={SETUP_SQL} onCopy={handleCopySql} copied={copied} />}
            {styles.length === 0 ? <EmptyState message="No styles found." /> : (
              <Table 
                headers={['Name', 'Difficulty', 'Duration', 'Benefits', 'Actions']}
                rows={styles.map((style, i) => (
                  <tr key={i} className="hover:bg-gray-50 border-b border-gray-100">
                    <td className="px-6 py-4 flex items-center gap-3 text-left">
                      <div className="w-10 h-10 rounded-lg bg-gray-100 overflow-hidden shrink-0">
                        {style.image ? <img src={style.image} alt={style.name} className="w-full h-full object-cover" /> : <ImageIcon size={16} />}
                      </div>
                      <span className="font-medium">{style.name}</span>
                    </td>
                    <td className="px-6 py-4 text-left"><Badge type={style.difficulty}>{style.difficulty}</Badge></td>
                    <td className="px-6 py-4 text-sm text-gray-600 text-left">{style.duration}</td>
                    <td className="px-6 py-4 text-sm text-gray-500 max-w-xs truncate text-left">{style.benefits.join(', ')}</td>
                    <td className="px-6 py-4 text-left">
                      <ActionButtons 
                        onEdit={() => { 
                          setEditingStyle(style); 
                          setStyleFormData({ name: style.name, description: style.description, benefits: style.benefits.join(', '), difficulty: style.difficulty, duration: style.duration });
                          setImagePreview(style.image);
                          setIsStyleModalOpen(true);
                        }} 
                        onDelete={() => handleDeleteStyle(style.slug, style.image)} 
                      />
                    </td>
                  </tr>
                ))}
              />
            )}
          </DashboardSection>
        );
      case 'schedule':
        return (
          <DashboardSection 
            title="Class Schedule" 
            description="Update weekly class timings and instructor assignments."
            onAdd={() => { resetScheduleForm(); setIsScheduleModalOpen(true); }}
            extraHeaderAction={<button onClick={() => setShowSqlHelp(!showSqlHelp)} className="text-xs text-gray-500 hover:text-deep-green underline flex items-center gap-1"><Terminal size={14} /> {showSqlHelp ? 'Hide SQL' : 'Show SQL'}</button>}
          >
            {showSqlHelp && <SqlHelpBox sql={SETUP_SQL} onCopy={handleCopySql} copied={copied} />}
            {scheduleData.length === 0 ? <EmptyState message="No classes scheduled." /> : (
              <Table 
                headers={['Day', 'Time', 'Class Name', 'Instructor', 'Location', 'Level', 'Actions']}
                rows={scheduleData.map((session, i) => (
                  <tr key={i} className="hover:bg-gray-50 border-b border-gray-100">
                    <td className="px-6 py-4 font-medium text-left">{session.day}</td>
                    <td className="px-6 py-4 text-sage-green font-medium whitespace-nowrap text-left">{session.time}</td>
                    <td className="px-6 py-4 text-left">{session.classType}</td>
                    <td className="px-6 py-4 text-sm text-gray-600 text-left">{session.instructor}</td>
                    <td className="px-6 py-4 text-sm text-gray-500 text-left">{session.location}</td>
                    <td className="px-6 py-4 text-left"><Badge>{session.level}</Badge></td>
                    <td className="px-6 py-4 text-left">
                      <ActionButtons onEdit={() => { setEditingSession(session); setScheduleFormData({...session}); setIsScheduleModalOpen(true); }} onDelete={() => handleDeleteSession(session.id)} />
                    </td>
                  </tr>
                ))}
              />
            )}
          </DashboardSection>
        );
      case 'programs':
        return (
          <DashboardSection 
            title="Programs" 
            description="Manage detailed course offerings and workshops." 
            onAdd={() => { resetProgramForm(); setIsProgramModalOpen(true); }}
            extraHeaderAction={<button onClick={() => setShowSqlHelp(!showSqlHelp)} className="text-xs text-gray-500 hover:text-deep-green underline flex items-center gap-1"><Terminal size={14} /> {showSqlHelp ? 'Hide SQL' : 'Show SQL'}</button>}
          >
            {showSqlHelp && <SqlHelpBox sql={SETUP_SQL} onCopy={handleCopySql} copied={copied} />}
            {programs.length === 0 ? <EmptyState message="No programs found." /> : (
              <Table 
                headers={['Program', 'Level', 'Duration', 'Price', 'PDF', 'Badge', 'Actions']}
                rows={programs.map((course, i) => (
                  <tr key={i} className="hover:bg-gray-50 border-b border-gray-100">
                    <td className="px-6 py-4 flex items-center gap-3 text-left">
                       <div className="w-10 h-10 rounded-lg bg-gray-100 overflow-hidden shrink-0">
                         {course.image ? <img src={course.image} alt={course.title} className="w-full h-full object-cover" /> : <ImageIcon size={16} />}
                       </div>
                       <div><div className="font-medium">{course.title}</div><div className="text-xs text-gray-400 truncate max-w-[150px]">{course.description}</div></div>
                    </td>
                    <td className="px-6 py-4 text-left"><Badge>{course.level}</Badge></td>
                    <td className="px-6 py-4 text-sm text-gray-600 text-left">{course.duration}</td>
                    <td className="px-6 py-4 font-medium text-deep-green text-left">₹{course.price}</td>
                    <td className="px-6 py-4 text-left">{course.pdf_url ? <a href={course.pdf_url} target="_blank" rel="noopener noreferrer" className="text-sage-green hover:underline flex items-center gap-1 text-xs"><FileText size={14} /> View</a> : <span className="text-gray-300">-</span>}</td>
                    <td className="px-6 py-4 text-left">{course.badge ? <span className="bg-yellow-100 text-yellow-800 text-xs px-2 py-1 rounded-full">{course.badge}</span> : <span className="text-gray-300">-</span>}</td>
                    <td className="px-6 py-4 text-left">
                      <ActionButtons 
                        onEdit={() => {
                          setEditingProgram(course);
                          setProgramFormData({ title: course.title, description: course.description, level: course.level, duration: course.duration, price: course.price.toString(), badge: course.badge || '' });
                          setImagePreview(course.image);
                          setSelectedPdf(null); // Reset file input
                          setIsProgramModalOpen(true);
                        }} 
                        onDelete={() => handleDeleteProgram(course.slug)} 
                      />
                    </td>
                  </tr>
                ))}
              />
            )}
          </DashboardSection>
        );
      case 'pricing':
        return (
           <DashboardSection 
            title="Pricing Plans" 
            description="Adjust membership costs and benefits." 
            onAdd={() => { resetPricingForm(); setIsPricingModalOpen(true); }}
            extraHeaderAction={<button onClick={() => setShowSqlHelp(!showSqlHelp)} className="text-xs text-gray-500 hover:text-deep-green underline flex items-center gap-1"><Terminal size={14} /> {showSqlHelp ? 'Hide SQL' : 'Show SQL'}</button>}
           >
            {showSqlHelp && <SqlHelpBox sql={SETUP_SQL} onCopy={handleCopySql} copied={copied} />}
            {pricingPlansData.length === 0 ? <EmptyState message="No pricing plans found." /> : (
              <Table 
                headers={['Plan Name', 'Price', 'Period', 'Highlighted', 'Benefits Count', 'Actions']}
                rows={pricingPlansData.map((plan, i) => (
                  <tr key={i} className="hover:bg-gray-50 border-b border-gray-100">
                    <td className="px-6 py-4 font-medium text-left">{plan.name}</td>
                    <td className="px-6 py-4 font-bold text-deep-green text-left">{formatAdminPrice(plan.price)}</td>
                    <td className="px-6 py-4 text-sm text-gray-600 capitalize text-left">{plan.period}</td>
                    <td className="px-6 py-4 text-left">{plan.highlight ? <span className="px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">Active</span> : <span className="text-gray-400 text-sm">Standard</span>}</td>
                    <td className="px-6 py-4 text-sm text-gray-500 text-left">{plan.benefits.length} items</td>
                    <td className="px-6 py-4 text-left">
                      <ActionButtons 
                        onEdit={() => {
                          setEditingPlan(plan);
                          setPricingFormData({ name: plan.name, price: plan.price, period: plan.period, benefits: plan.benefits.join(', '), highlight: plan.highlight });
                          setIsPricingModalOpen(true);
                        }} 
                        onDelete={() => handleDeletePlan(plan.id)} 
                      />
                    </td>
                  </tr>
                ))}
              />
            )}
          </DashboardSection>
        );
      case 'messages':
         const handleSort = (key: keyof ContactInquiry) => {
            let direction: 'asc' | 'desc' = 'asc';
            if (messageSort.key === key && messageSort.direction === 'asc') {
                direction = 'desc';
            }
            setMessageSort({ key, direction });
         };

         const sortedMessages = [...inquiries].sort((a, b) => {
             const aValue = a[messageSort.key] || '';
             const bValue = b[messageSort.key] || '';
             
             if (messageSort.key === 'created_at') {
                 return messageSort.direction === 'asc' 
                    ? new Date(aValue).getTime() - new Date(bValue).getTime()
                    : new Date(bValue).getTime() - new Date(aValue).getTime();
             }

             if (aValue < bValue) return messageSort.direction === 'asc' ? -1 : 1;
             if (aValue > bValue) return messageSort.direction === 'asc' ? 1 : -1;
             return 0;
         });

         const indexOfLastMsg = messagePage * messagesPerPage;
         const indexOfFirstMsg = indexOfLastMsg - messagesPerPage;
         const currentMessages = sortedMessages.slice(indexOfFirstMsg, indexOfLastMsg);
         const totalPages = Math.ceil(inquiries.length / messagesPerPage);

         return (
          <DashboardSection 
            title="Contact Inquiries" 
            description="View messages from customers." 
            onAdd={() => {}} 
            hideAddButton={true}
            extraHeaderAction={
              <button onClick={exportInquiriesToCSV} className="text-xs text-deep-green hover:bg-sage-green/10 border border-sage-green/30 px-3 py-1.5 rounded-md flex items-center gap-2 transition-colors shadow-sm text-left">
                <Download size={14} /> Export Excel
              </button>
            }
          >
            {inquiries.length === 0 ? <EmptyState message="No inquiries." /> : (
               <>
                 <div className="overflow-x-auto text-left">
                    <table className="w-full text-left border-collapse">
                      <thead>
                        <tr className="bg-gray-50/50 border-b border-gray-100 text-xs font-semibold text-gray-500 uppercase tracking-wider">
                          <th className="px-6 py-4 cursor-pointer hover:text-deep-green transition-colors select-none" onClick={() => handleSort('created_at')}>
                            <div className="flex items-center gap-1">Date <ArrowUpDown size={12}/></div>
                          </th>
                          <th className="px-6 py-4 cursor-pointer hover:text-deep-green transition-colors select-none" onClick={() => handleSort('inquiry_type')}>
                            <div className="flex items-center gap-1">Type <ArrowUpDown size={12}/></div>
                          </th>
                          <th className="px-6 py-4 cursor-pointer hover:text-deep-green transition-colors select-none" onClick={() => handleSort('first_name')}>
                            <div className="flex items-center gap-1">Name <ArrowUpDown size={12}/></div>
                          </th>
                          <th className="px-6 py-4">Contact Info</th>
                          <th className="px-6 py-4">Message</th>
                          <th className="px-6 py-4">Actions</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-50">
                        {currentMessages.map((inquiry, i) => (
                          <tr key={inquiry.id} className="hover:bg-gray-50 border-b border-gray-100">
                            <td className="px-6 py-4 text-sm text-gray-500 whitespace-nowrap text-left">{formatAdminDate(inquiry.created_at)}</td>
                            <td className="px-6 py-4 text-left">
                                <span className={`text-xs px-2 py-1 rounded-full font-medium ${
                                    inquiry.inquiry_type?.startsWith('Book') ? 'bg-blue-100 text-blue-800' : 'bg-gray-100 text-gray-800'
                                }`}>
                                    {inquiry.inquiry_type || 'General'}
                                </span>
                            </td>
                            <td className="px-6 py-4 font-medium text-left">{inquiry.first_name} {inquiry.last_name}</td>
                            <td className="px-6 py-4 text-sm text-gray-600 text-left">
                                <a href={`mailto:${inquiry.email}`} className="block hover:text-deep-green hover:underline">{inquiry.email}</a>
                                {inquiry.phone_number && <a href={`tel:${inquiry.phone_number}`} className="block text-gray-400 hover:text-deep-green text-xs mt-1">{inquiry.phone_number}</a>}
                            </td>
                            <td className="px-6 py-4 text-sm text-gray-600 max-w-sm truncate text-left">{inquiry.message}</td>
                            <td className="px-6 py-4 text-left"><button onClick={() => handleDeleteInquiry(inquiry.id)} className="p-1.5 text-gray-500 hover:text-red-600 hover:bg-red-50 rounded-md" title="Delete"><Trash2 size={16} /></button></td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                 </div>

                 {totalPages > 1 && (
                    <div className="px-6 py-4 flex items-center justify-between border-t border-gray-100">
                        <span className="text-xs text-gray-500">
                            Showing {indexOfFirstMsg + 1} to {Math.min(indexOfLastMsg, inquiries.length)} of {inquiries.length} results
                        </span>
                        <div className="flex items-center gap-2">
                            <button 
                                onClick={() => setMessagePage(Math.max(1, messagePage - 1))}
                                disabled={messagePage === 1}
                                className="p-1 rounded-md hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed text-gray-500"
                            >
                                <ChevronLeft size={16} />
                            </button>
                            
                            {[...Array(totalPages)].map((_, idx) => {
                                const pageNum = idx + 1;
                                if (totalPages > 7 && Math.abs(pageNum - messagePage) > 2 && pageNum !== 1 && pageNum !== totalPages) {
                                   if (Math.abs(pageNum - messagePage) === 3) return <span key={pageNum} className="text-xs text-gray-300">...</span>;
                                   return null;
                                }

                                return (
                                    <button
                                        key={pageNum}
                                        onClick={() => setMessagePage(pageNum)}
                                        className={`w-7 h-7 flex items-center justify-center rounded-md text-xs font-medium transition-colors ${
                                            messagePage === pageNum 
                                            ? 'bg-sage-green text-white' 
                                            : 'text-gray-600 hover:bg-gray-100'
                                        }`}
                                    >
                                        {pageNum}
                                    </button>
                                )
                            })}

                            <button 
                                onClick={() => setMessagePage(Math.min(totalPages, messagePage + 1))}
                                disabled={messagePage === totalPages}
                                className="p-1 rounded-md hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed text-gray-500"
                            >
                                <ChevronRight size={16} />
                            </button>
                        </div>
                    </div>
                 )}
               </>
            )}
          </DashboardSection>
        );

        case 'feedback':
            return (
              <DashboardSection 
                title="Customer Feedback" 
                description="Manage testimonials displayed on the 'Stories from the Mat' section."
                onAdd={() => { resetFeedbackForm(); setIsFeedbackModalOpen(true); }}
                extraHeaderAction={<button onClick={() => setShowSqlHelp(!showSqlHelp)} className="text-xs text-gray-500 hover:text-deep-green underline flex items-center gap-1"><Terminal size={14} /> {showSqlHelp ? 'Hide SQL' : 'Show SQL'}</button>}
              >
                {showSqlHelp && <SqlHelpBox sql={SETUP_SQL} onCopy={handleCopySql} copied={copied} />}
                {feedback.length === 0 ? <EmptyState message="No feedback found." /> : (
                  <Table 
                    headers={['Name', 'Role', 'Rating', 'Quote', 'Actions']}
                    rows={feedback.map((item, i) => (
                      <tr key={i} className="hover:bg-gray-50 border-b border-gray-100">
                        <td className="px-6 py-4 flex items-center gap-3 text-left">
                           <div className="w-10 h-10 rounded-full bg-gray-100 overflow-hidden shrink-0">
                             {item.image ? <img src={item.image} alt={item.name} className="w-full h-full object-cover" /> : <User size={20} className="m-auto mt-2 text-gray-400" />}
                           </div>
                           <span className="font-medium">{item.name}</span>
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-600 text-left">{item.role}</td>
                        <td className="px-6 py-4 flex gap-1 text-left">
                            {[...Array(5)].map((_, i) => (
                                <Star key={i} size={14} className={i < item.rating ? "fill-yellow-400 text-yellow-400" : "text-gray-300"} />
                            ))}
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-500 max-w-xs truncate italic text-left">"{item.quote}"</td>
                        <td className="px-6 py-4 text-left">
                          <ActionButtons 
                            onEdit={() => {
                              setEditingFeedback(item);
                              setFeedbackFormData({ 
                                  name: item.name, 
                                  role: item.role, 
                                  quote: item.quote, 
                                  rating: item.rating, 
                                  image: item.image 
                              });
                              setImagePreview(item.image);
                              setIsFeedbackModalOpen(true);
                            }} 
                            onDelete={() => handleDeleteFeedback(item.id)} 
                          />
                        </td>
                      </tr>
                    ))}
                  />
                )}
              </DashboardSection>
            );

      case 'blog':
        return (
          <DashboardSection 
            title="Blog Posts" 
            description="Manage your wellness blog. Published posts appear on the website."
            onAdd={() => { resetBlogForm(); setIsBlogModalOpen(true); }}
            extraHeaderAction={<button onClick={() => setShowSqlHelp(!showSqlHelp)} className="text-xs text-gray-500 hover:text-deep-green underline flex items-center gap-1"><Terminal size={14} /> {showSqlHelp ? 'Hide SQL' : 'Show SQL'}</button>}
          >
            {showSqlHelp && <SqlHelpBox sql={SETUP_SQL} onCopy={handleCopySql} copied={copied} />}
            {blogPosts.length === 0 ? <EmptyState message="No blog posts yet." /> : (
              <Table 
                headers={['Post', 'Status', 'Category', 'Date', 'Stats', 'Actions']}
                rows={blogPosts.map((post, i) => (
                  <tr key={i} className="hover:bg-gray-50 border-b border-gray-100">
                    <td className="px-6 py-4 flex items-center gap-3 text-left">
                       <div className="w-10 h-10 rounded-lg bg-gray-100 overflow-hidden shrink-0">
                          {post.image ? <img src={post.image} alt={post.title} className="w-full h-full object-cover" /> : <ImageIcon size={16} />}
                       </div>
                       <div className="overflow-hidden">
                         <div className="font-medium truncate max-w-[200px]">{post.title}</div>
                         <div className="text-xs text-gray-400 truncate max-w-[200px]">{post.excerpt}</div>
                       </div>
                    </td>
                    <td className="px-6 py-4 text-left"><Badge type={post.published ? 'published' : 'draft'}>{post.published ? 'Published' : 'Draft'}</Badge></td>
                    <td className="px-6 py-4 text-left"><span className="bg-sage-green/10 text-deep-green px-2 py-1 rounded text-xs font-medium uppercase tracking-wide">{post.category}</span></td>
                    <td className="px-6 py-4 text-sm text-gray-500 text-left">{new Date(post.created_at).toLocaleDateString()}</td>
                    <td className="px-6 py-4 text-sm text-gray-400 text-left">{post.likes} likes</td>
                    <td className="px-6 py-4 text-left">
                      <ActionButtons 
                        onEdit={() => {
                          setEditingPost(post);
                          setBlogFormData({ 
                            title: post.title, 
                            slug: post.slug, 
                            excerpt: post.excerpt, 
                            content: post.content, 
                            category: post.category, 
                            published: post.published,
                            image: post.image || ''
                          });
                          setImagePreview(post.image);
                          setIsBlogModalOpen(true);
                        }} 
                        onDelete={() => handleDeletePost(post.id)} 
                      />
                    </td>
                  </tr>
                ))}
              />
            )}
          </DashboardSection>
        );

      default:
        return <div>Select a menu item</div>;
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex font-sans">
      <aside className="hidden md:flex flex-col w-64 bg-deep-green text-white fixed top-0 left-0 h-screen z-20 shadow-xl">
        <div className="p-6 border-b border-white/10 shrink-0">
          <h2 className="font-serif text-2xl font-bold tracking-wide flex items-center gap-2">
            Meraki <span className="text-[10px] bg-sage-green text-deep-green px-1.5 py-0.5 rounded uppercase font-sans font-bold tracking-wider">Admin</span>
          </h2>
        </div>
        <nav className="flex-1 py-6 px-3 space-y-1 overflow-y-auto min-h-0 scrollbar-thin scrollbar-thumb-white/20 scrollbar-track-transparent">
          {menuItems.map((item) => (
            <button key={item.id} onClick={() => setActiveTab(item.id)} className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium transition-all duration-200 ${activeTab === item.id ? 'bg-sage-green text-deep-green shadow-md translate-x-1' : 'text-gray-300 hover:bg-white/5 hover:text-white'}`}>
              {item.icon}
              {item.label}
            </button>
          ))}
        </nav>
        <div className="p-4 border-t border-white/10 bg-black/10 shrink-0">
          <div className="flex items-center gap-3 px-4 py-3 mb-2">
            <div className="w-8 h-8 rounded-full bg-sage-green flex items-center justify-center text-deep-green font-bold shadow-sm">{userEmail.charAt(0).toUpperCase()}</div>
            <div className="overflow-hidden"><p className="text-sm font-medium truncate text-white">{userEmail}</p><p className="text-xs text-sage-green/80">Administrator</p></div>
          </div>
          <button onClick={handleLogout} className="w-full flex items-center gap-2 px-4 py-2 text-sm text-red-300 hover:text-red-200 hover:bg-red-900/20 rounded-lg transition-colors"><LogOut size={16} /> Sign Out</button>
        </div>
      </aside>

      <div className="md:hidden fixed w-full bg-deep-green text-white z-20 flex justify-between items-center p-4 shadow-md">
        <span className="font-serif text-xl font-bold">Meraki Admin</span>
        <button onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}>{isMobileMenuOpen ? <X size={24} /> : <Menu size={24} />}</button>
      </div>

      {isMobileMenuOpen && (
        <div className="md:hidden fixed inset-0 bg-black/50 z-30 backdrop-blur-sm" onClick={() => setIsMobileMenuOpen(false)}>
          <motion.div initial={{ x: -300 }} animate={{ x: 0 }} className="bg-deep-green text-white h-[100dvh] w-72 p-4 flex flex-col shadow-2xl" onClick={e => e.stopPropagation()}>
             <div className="p-4 border-b border-white/10 mb-4 shrink-0"><span className="font-serif text-2xl font-bold">Menu</span></div>
             <nav className="flex-1 space-y-2 overflow-y-auto min-h-0">
              {menuItems.map((item) => (
                <button key={item.id} onClick={() => { setActiveTab(item.id); setIsMobileMenuOpen(false); }} className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium transition-colors ${activeTab === item.id ? 'bg-sage-green text-deep-green' : 'text-gray-300 hover:bg-white/5 hover:text-white'}`}>
                  {item.icon}
                  {item.label}
                </button>
              ))}
            </nav>
            <div className="mt-auto border-t border-white/10 shrink-0"><button onClick={handleLogout} className="w-full flex items-center gap-2 px-4 py-4 text-red-300 hover:bg-red-900/20 rounded-lg"><LogOut size={18} /> Sign Out</button></div>
          </motion.div>
        </div>
      )}

      <main className="flex-1 md:ml-64 p-4 md:p-8 pt-20 md:pt-8 min-h-screen transition-all">
        <div className="max-w-6xl mx-auto">{renderContent()}</div>
      </main>

      <Modal isOpen={isStyleModalOpen} onClose={() => setIsStyleModalOpen(false)} title={editingStyle ? 'Edit Yoga Style' : 'Add New Style'}>
        <form onSubmit={handleStyleSubmit} className="space-y-6">
            <div className="space-y-2 text-left"><label className="text-sm font-semibold text-gray-700">Cover Image</label>
            <div className="flex items-center gap-6"><div className="w-32 h-32 rounded-lg bg-gray-100 border-2 border-dashed border-gray-300 flex items-center justify-center overflow-hidden relative">{imagePreview ? <img src={imagePreview} alt="Preview" className="w-full h-full object-cover" /> : <Upload className="text-gray-400" size={24} />}</div><div className="flex-1"><input type="file" accept="image/*" onChange={handleImageChange} id="style-image" className="hidden" /><label htmlFor="style-image" className="inline-block px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 cursor-pointer hover:bg-gray-50 transition-colors shadow-sm">{editingStyle ? 'Change Image' : 'Choose File'}</label><p className="text-xs text-gray-500 mt-2">Recommended: 800x600px (JPG, PNG)</p></div></div></div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-left"><div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Style Name</label><input type="text" required value={styleFormData.name} onChange={e => setStyleFormData({...styleFormData, name: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. Vinyasa Flow" /></div><div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Duration</label><input type="text" required value={styleFormData.duration} onChange={e => setStyleFormData({...styleFormData, duration: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. 60 mins" /></div></div>
            <div className="space-y-2 text-left"><label className="text-sm font-semibold text-gray-700">Difficulty Level</label><div className="flex gap-4">{['Beginner', 'Intermediate', 'Advanced'].map(level => (<label key={level} className="flex items-center gap-2 cursor-pointer"><input type="radio" name="difficulty" value={level} checked={styleFormData.difficulty === level} onChange={e => setStyleFormData({...styleFormData, difficulty: e.target.value})} className="text-sage-green focus:ring-sage-green" /><span className="text-sm text-gray-600">{level}</span></label>))}</div></div>
            <div className="space-y-2 text-left"><label className="text-sm font-semibold text-gray-700">Description</label><textarea required rows={3} value={styleFormData.description} onChange={e => setStyleFormData({...styleFormData, description: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="Brief description..." /></div>
            <div className="space-y-2 text-left"><label className="text-sm font-semibold text-gray-700">Benefits (Comma Separated)</label><input type="text" value={styleFormData.benefits} onChange={e => setStyleFormData({...styleFormData, benefits: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="Flexibility, Strength..." /></div>
            <div className="pt-4 flex justify-end gap-3"><button type="button" onClick={() => setIsStyleModalOpen(false)} className="px-6 py-2 text-gray-600 font-medium hover:bg-gray-100 rounded-lg">Cancel</button><button type="submit" disabled={isSubmitting} className="px-6 py-2 bg-deep-green text-white font-medium rounded-lg hover:bg-opacity-90 flex items-center gap-2">{isSubmitting ? <Loader2 className="animate-spin" size={18} /> : (editingStyle ? 'Update Style' : 'Create Style')}</button></div>
        </form>
      </Modal>

      <Modal isOpen={isScheduleModalOpen} onClose={() => setIsScheduleModalOpen(false)} title={editingSession ? 'Edit Class Session' : 'Add Class Session'}>
        <form onSubmit={handleScheduleSubmit} className="space-y-6">
           <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-left">
                <div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Day of Week</label><div className="relative"><Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} /><select value={scheduleFormData.day} onChange={e => setScheduleFormData({...scheduleFormData, day: e.target.value})} className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none appearance-none bg-white">{['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map(day => (<option key={day} value={day}>{day}</option>))}</select></div></div>
                <div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Time</label><div className="relative"><Clock className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} /><input type="text" required value={scheduleFormData.time} onChange={e => setScheduleFormData({...scheduleFormData, time: e.target.value})} className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. 07:00 AM" /></div></div>
            </div>
            <div className="space-y-2 text-left"><label className="text-sm font-semibold text-gray-700">Class Name</label><input type="text" required value={scheduleFormData.classType} onChange={e => setScheduleFormData({...scheduleFormData, classType: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. Morning Flow" /></div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-left"><div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Instructor</label><div className="relative"><User className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} /><input type="text" required value={scheduleFormData.instructor} onChange={e => setScheduleFormData({...scheduleFormData, instructor: e.target.value})} className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. Sarah J." /></div></div><div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Location</label><div className="relative"><MapPin className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} /><input type="text" required value={scheduleFormData.location} onChange={e => setScheduleFormData({...scheduleFormData, location: e.target.value})} className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. Studio A" /></div></div></div>
            <div className="space-y-2 text-left"><label className="text-sm font-semibold text-gray-700">Difficulty Level</label><select value={scheduleFormData.level} onChange={e => setScheduleFormData({...scheduleFormData, level: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none bg-white"><option>All Levels</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Open</option></select></div>
            <div className="pt-4 flex justify-end gap-3"><button type="button" onClick={() => setIsScheduleModalOpen(false)} className="px-6 py-2 text-gray-600 font-medium hover:bg-gray-100 rounded-lg">Cancel</button><button type="submit" disabled={isSubmitting} className="px-6 py-2 bg-deep-green text-white font-medium rounded-lg hover:bg-opacity-90 flex items-center gap-2">{isSubmitting ? <Loader2 className="animate-spin" size={18} /> : (editingSession ? 'Update Session' : 'Add Session')}</button></div>
        </form>
      </Modal>

      <Modal isOpen={isProgramModalOpen} onClose={() => setIsProgramModalOpen(false)} title={editingProgram ? 'Edit Program' : 'Add New Program'}>
        <form onSubmit={handleProgramSubmit} className="space-y-6">
            <div className="space-y-2 text-left"><label className="text-sm font-semibold text-gray-700">Program Image</label>
            <div className="flex items-center gap-6"><div className="w-32 h-32 rounded-lg bg-gray-100 border-2 border-dashed border-gray-300 flex items-center justify-center overflow-hidden relative">{imagePreview ? <img src={imagePreview} alt="Preview" className="w-full h-full object-cover" /> : <Upload className="text-gray-400" size={24} />}</div><div className="flex-1"><input type="file" accept="image/*" onChange={handleImageChange} id="program-image" className="hidden" /><label htmlFor="program-image" className="inline-block px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 cursor-pointer hover:bg-gray-50 transition-colors shadow-sm">{editingProgram ? 'Change Image' : 'Choose File'}</label><p className="text-xs text-gray-500 mt-2">Recommended: 800x600px (JPG, PNG)</p></div></div></div>
            
            <div className="space-y-2 text-left">
                <label className="text-sm font-semibold text-gray-700">Program PDF (Syllabus/Brochure)</label>
                <div className="flex items-center gap-4">
                    <div className="flex-1">
                        <input type="file" accept="application/pdf" onChange={handlePdfChange} id="program-pdf" className="hidden" />
                        <label htmlFor="program-pdf" className="inline-flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 cursor-pointer hover:bg-gray-50 transition-colors shadow-sm text-left">
                            <Upload size={16} /> {selectedPdf ? 'Change PDF' : (editingProgram?.pdf_url ? 'Replace PDF' : 'Upload PDF')}
                        </label>
                        {selectedPdf && <span className="ml-3 text-sm text-gray-600 truncate">{selectedPdf.name}</span>}
                        {!selectedPdf && editingProgram?.pdf_url && <span className="ml-3 text-sm text-green-600 flex items-center gap-1 text-left"><Check size={14}/> PDF Linked</span>}
                    </div>
                </div>
            </div>

            <div className="space-y-2 text-left"><label className="text-sm font-semibold text-gray-700">Program Title</label><input type="text" required value={programFormData.title} onChange={e => setProgramFormData({...programFormData, title: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. 4-Week Beginner Course" /></div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-left"><div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Level</label><select value={programFormData.level} onChange={e => setProgramFormData({...programFormData, level: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none bg-white"><option>All Levels</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div><div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Duration</label><input type="text" required value={programFormData.duration} onChange={e => setProgramFormData({...programFormData, duration: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. 4 Weeks" /></div></div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-left"><div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Price (₹)</label><div className="relative"><IndianRupee className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} /><input type="number" required value={programFormData.price} onChange={e => setProgramFormData({...programFormData, price: e.target.value})} className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. 99" /></div></div><div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Badge (Optional)</label><input type="text" value={programFormData.badge} onChange={e => setProgramFormData({...programFormData, badge: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. Most Popular" /></div></div>
            {/* Fix malformed onChange handler here */}
            <div className="space-y-2 text-left"><label className="text-sm font-semibold text-gray-700">Description</label><textarea required rows={3} value={programFormData.description} onChange={e => setProgramFormData({...programFormData, description: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="Describe the program..." /></div>
            <div className="pt-4 flex justify-end gap-3"><button type="button" onClick={() => setIsProgramModalOpen(false)} className="px-6 py-2 text-gray-600 font-medium hover:bg-gray-100 rounded-lg">Cancel</button><button type="submit" disabled={isSubmitting} className="px-6 py-2 bg-deep-green text-white font-medium rounded-lg hover:bg-opacity-90 flex items-center gap-2">{isSubmitting ? <Loader2 className="animate-spin" size={18} /> : (editingProgram ? 'Update Program' : 'Create Program')}</button></div>
        </form>
      </Modal>

      <Modal isOpen={isPricingModalOpen} onClose={() => setIsPricingModalOpen(false)} title={editingPlan ? 'Edit Pricing Plan' : 'Add New Plan'}>
        <form onSubmit={handlePricingSubmit} className="space-y-6 text-left">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Plan Name</label><input type="text" required value={pricingFormData.name} onChange={e => setPricingFormData({...pricingFormData, name: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. Unlimited Monthly" /></div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-gray-700">Price Display</label>
                <div className="relative">
                  <IndianRupee className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                  <input type="text" required value={pricingFormData.price} onChange={e => setPricingFormData({...pricingFormData, price: e.target.value})} className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. 2500" />
                </div>
              </div>
            </div>
            <div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Billing Period</label><input type="text" required value={pricingFormData.period} onChange={e => setPricingFormData({...pricingFormData, period: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. per month" /></div>
            <div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Benefits (Comma Separated)</label><textarea required rows={4} value={pricingFormData.benefits} onChange={e => setPricingFormData({...pricingFormData, benefits: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="Unlimited classes, Free mat rental..." /></div>
            <div className="flex items-center gap-3 bg-gray-50 p-3 rounded-lg"><input type="checkbox" id="highlight" checked={pricingFormData.highlight} onChange={e => setPricingFormData({...pricingFormData, highlight: e.target.checked})} className="w-5 h-5 text-sage-green rounded border-gray-300 focus:ring-sage-green" /><label htmlFor="highlight" className="text-sm font-medium text-gray-700">Highlight this plan (Best Value)</label></div>
            <div className="pt-4 flex justify-end gap-3"><button type="button" onClick={() => setIsPricingModalOpen(false)} className="px-6 py-2 text-gray-600 font-medium hover:bg-gray-100 rounded-lg">Cancel</button><button type="submit" disabled={isSubmitting} className="px-6 py-2 bg-deep-green text-white font-medium rounded-lg hover:bg-opacity-90 flex items-center gap-2">{isSubmitting ? <Loader2 className="animate-spin" size={18} /> : (editingPlan ? 'Update Plan' : 'Create Plan')}</button></div>
        </form>
      </Modal>

      <Modal isOpen={isBlogModalOpen} onClose={() => setIsBlogModalOpen(false)} title={editingPost ? 'Edit Blog Post' : 'Create Blog Post'}>
        <form onSubmit={handleBlogSubmit} className="space-y-6 text-left">
            <div className="space-y-2"><label className="text-sm font-semibold text-gray-700">Featured Image</label>
            <div className="flex items-center gap-6"><div className="w-32 h-32 rounded-lg bg-gray-100 border-2 border-dashed border-gray-300 flex items-center justify-center overflow-hidden relative">{imagePreview ? <img src={imagePreview} alt="Preview" className="w-full h-full object-cover" /> : <Upload className="text-gray-400" size={24} />}</div><div className="flex-1"><input type="file" accept="image/*" onChange={handleImageChange} id="blog-image" className="hidden" /><label htmlFor="blog-image" className="inline-block px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 cursor-pointer hover:bg-gray-50 transition-colors shadow-sm">{editingPost ? 'Change Image' : 'Choose File'}</label><p className="text-xs text-gray-500 mt-2">Recommended: 800x400px (JPG, PNG)</p></div></div></div>
            
            <div className="space-y-2">
                <label className="text-sm font-semibold text-gray-700">Title</label>
                <input type="text" required value={blogFormData.title} onChange={e => setBlogFormData({...blogFormData, title: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="Enter post title" />
            </div>
            
            <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                    <label className="text-sm font-semibold text-gray-700">Category</label>
                    <input type="text" value={blogFormData.category} onChange={e => setBlogFormData({...blogFormData, category: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. Wellness" />
                </div>
                <div className="space-y-2">
                    <label className="text-sm font-semibold text-gray-700">Slug (Optional)</label>
                    <input type="text" value={blogFormData.slug} onChange={e => setBlogFormData({...blogFormData, slug: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="auto-generated-if-empty" />
                </div>
            </div>

            <div className="space-y-2">
                <label className="text-sm font-semibold text-gray-700">Excerpt (Short Summary)</label>
                <textarea rows={2} value={blogFormData.excerpt} onChange={e => setBlogFormData({...blogFormData, excerpt: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="Appears on the main blog card..." />
            </div>

            <div className="space-y-2">
                <label className="text-sm font-semibold text-gray-700">Full Content</label>
                <textarea required rows={10} value={blogFormData.content} onChange={e => setBlogFormData({...blogFormData, content: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none font-mono text-sm" placeholder="Write your post here. Use paragraphs..." />
            </div>

            <div className="flex items-center gap-3 bg-gray-50 p-3 rounded-lg">
                <input type="checkbox" id="published" checked={blogFormData.published} onChange={e => setBlogFormData({...blogFormData, published: e.target.checked})} className="w-5 h-5 text-sage-green rounded border-gray-300 focus:ring-sage-green" />
                <label htmlFor="published" className="text-sm font-medium text-gray-700">Publish immediately</label>
            </div>

            <div className="pt-4 flex justify-end gap-3">
                <button type="button" onClick={() => setIsBlogModalOpen(false)} className="px-6 py-2 text-gray-600 font-medium hover:bg-gray-100 rounded-lg">Cancel</button>
                <button type="submit" disabled={isSubmitting} className="px-6 py-2 bg-deep-green text-white font-medium rounded-lg hover:bg-opacity-90 flex items-center gap-2">
                    {isSubmitting ? <Loader2 className="animate-spin" size={18} /> : (editingPost ? 'Update Post' : 'Create Post')}
                </button>
            </div>
        </form>
      </Modal>

      <Modal isOpen={isFeedbackModalOpen} onClose={() => setIsFeedbackModalOpen(false)} title={editingFeedback ? 'Edit Feedback' : 'Add Testimonial'}>
          <form onSubmit={handleFeedbackSubmit} className="space-y-6 text-left">
              <div className="space-y-2">
                  <label className="text-sm font-semibold text-gray-700">Customer Photo</label>
                  <div className="flex items-center gap-6">
                      <div className="w-20 h-20 rounded-full bg-gray-100 border-2 border-dashed border-gray-300 flex items-center justify-center overflow-hidden relative">
                          {imagePreview ? <img src={imagePreview} alt="Preview" className="w-full h-full object-cover" /> : <User className="text-gray-400" size={24} />}
                      </div>
                      <div className="flex-1">
                          <input type="file" accept="image/*" onChange={handleImageChange} id="feedback-image" className="hidden" />
                          <label htmlFor="feedback-image" className="inline-block px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 cursor-pointer hover:bg-gray-50 transition-colors shadow-sm">
                              {editingFeedback ? 'Change Photo' : 'Choose Photo'}
                          </label>
                      </div>
                  </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                      <label className="text-sm font-semibold text-gray-700">Customer Name</label>
                      <input type="text" required value={feedbackFormData.name} onChange={e => setFeedbackFormData({...feedbackFormData, name: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. Jane Doe" />
                  </div>
                  <div className="space-y-2">
                      <label className="text-sm font-semibold text-gray-700">Role / Title</label>
                      <input type="text" value={feedbackFormData.role} onChange={e => setFeedbackFormData({...feedbackFormData, role: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="e.g. Member since 2021" />
                  </div>
              </div>
              <div className="space-y-2">
                  <label className="text-sm font-semibold text-gray-700">Rating</label>
                  <div className="flex items-center gap-2">
                      {[1, 2, 3, 4, 5].map((star) => (
                          <button
                              key={star}
                              type="button"
                              onClick={() => setFeedbackFormData({...feedbackFormData, rating: star})}
                              className={`p-1 rounded-full transition-colors ${feedbackFormData.rating >= star ? 'text-yellow-400' : 'text-gray-300'}`}
                          >
                              <Star size={24} fill="currentColor" />
                          </button>
                      ))}
                      <span className="ml-2 text-sm text-gray-500">({feedbackFormData.rating} Stars)</span>
                  </div>
              </div>
              <div className="space-y-2">
                  <label className="text-sm font-semibold text-gray-700">Quote / Message</label>
                  <textarea required rows={4} value={feedbackFormData.quote} onChange={e => setFeedbackFormData({...feedbackFormData, quote: e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-sage-green outline-none" placeholder="Their testimonial..." />
              </div>
              <div className="pt-4 flex justify-end gap-3">
                  <button type="button" onClick={() => setIsFeedbackModalOpen(false)} className="px-6 py-2 text-gray-600 font-medium hover:bg-gray-100 rounded-lg">Cancel</button>
                  <button type="submit" disabled={isSubmitting} className="px-6 py-2 bg-deep-green text-white font-medium rounded-lg hover:bg-opacity-90 flex items-center gap-2">
                      {isSubmitting ? <Loader2 className="animate-spin" size={18} /> : (editingFeedback ? 'Update' : 'Add')}
                  </button>
              </div>
          </form>
      </Modal>

    </div>
  );
};

export default AdminDashboard;
